// `pnpm run make:load`: build the installer `curl -fsSL https://term.surf/load | sh` runs, as one file served beside
// the script: mesh/site/term.surf/home/public/load.mjs (deck/call/code/load-term.ts says what it does).
//
// EVERYTHING IS BUNDLED. The machine running it has Node and nothing else of term's yet, so every dependency travels
// inside the file. The port build runs first (the alias does it), because the output library is made of ports.
//
// It is GENERATED: change load-term.ts and its imports, never load.mjs, then run this and deploy term.surf.

import path from 'node:path'
import { statSync } from 'node:fs'
import { build } from 'esbuild'

const TERM = path.resolve(import.meta.dirname, '..')
const OUT = path.resolve(TERM, '..', '..', '..', '..', 'mesh', 'site', 'term.surf', 'home', 'public', 'load.mjs')

await build({
  absWorkingDir: TERM,
  entryPoints: ['deck/call/code/load-term.ts'],
  outfile: OUT,
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node22',
  minify: true,
  // the CommonJS dependencies bundled into an ES module still call `require` for node builtins
  banner: {
    js: [
      '// GENERATED by `pnpm run make:load` from deck/term/deck/term/deck/call/code/load-term.ts. Do not edit.',
      "import { createRequire as __termRequire } from 'node:module';",
      'const require = __termRequire(import.meta.url);',
    ].join('\n'),
  },
  // the optional Postgres driver the base engine imports on demand, which an install never reaches
  external: ['pg'],
  logLevel: 'warning',
})

console.log(`make-load: wrote ${path.relative(process.cwd(), OUT)}, ${(statSync(OUT).size / 1000).toFixed(1)} kB`)
