// Quantified FUNCTIONS and UNIVERSAL hypotheses in theorems (check/holds.ts applicationKey, universalGoal,
// universalInduction): a `mark x, like task` is a pure application, a `have h / mark t / P` holds for every t and is
// instantiated at the terms the goal names, and `fold n` inducts over a goal whose recurrences are such hypotheses.
// Every goal is decided over an ordered field. Run: npx tsx test/check/universal.ts
//
// GENERATED by deck/term/deck/seed.tree/tmp/gen/universal-suite.py from the library and control files, so it checks
// exactly what they state: the completeness of the reals, the fundamental theorem of calculus, cosh's derivative and
// Gauss-Bonnet, each refusal beside a statement that must still be proven.

import { compile } from '@term/make/code/compile/compile'

let pass = 0
let fail = 0

function expect(name: string, source: string, want: string): void {
  const result = compile({ file: 's.tree', text: source })
  const codes = result.ok ? [] : result.diagnostics.map(d => d.name)
  const good = want === 'ok' ? result.ok : !result.ok && codes.includes(want)

  if (good) {
    pass++
    console.log(`ok    ${name}`)
  } else {
    fail++
    console.log(`FAIL  ${name}  (ok=${result.ok}, codes=${codes.join(',')}, wanted ${want})`)
  }
}

expect(
  'a quantified function is a pure application',
  `
rule probe-function-mark
  mark x
    like task
      take n, like integer
      like integer
  mark n, like integer
  have nonnegative
    call is-minimum
      call x
        read n
      code 0
  show hold
    call is-above
      call add
        call x
          read n
        code 1
      code 0
`,
  'ok',
)

expect(
  'x(n) >= 0 does not give x(n + 1) >= 0',
  `
rule probe-function-mark-false
  mark x
    like task
      take n, like integer
      like integer
  mark n, like integer
  have nonnegative
    call is-minimum
      call x
        read n
      code 0
  show hold
    call is-minimum
      call x
        call add
          read n
          code 1
      code 0
`,
  'unproven',
)

expect(
  'a universal hypothesis chains through two instances',
  `
rule probe-universal-chain
  mark x
    like task
      take t, like integer
      like integer
  mark n, like integer
  have non-decreasing
    mark t, like integer
    call is-maximum
      call x
        read t
      call x
        call add
          read t
          code 1
  show hold
    call is-maximum
      call x
        read n
      call x
        call add
          read n
          code 2
`,
  'ok',
)

expect(
  'and is not read backwards',
  `
rule probe-universal-false
  mark x
    like task
      take t, like integer
      like integer
  mark n, like integer
  have non-decreasing
    mark t, like integer
    call is-maximum
      call x
        read t
      call x
        call add
          read t
          code 1
  show hold
    call is-maximum
      call x
        call add
          read n
          code 2
      call x
        read n
`,
  'unproven',
)

expect(
  'the limit of a Cauchy sequence of reals is a real',
  `
rule the-limit-is-a-real
  mark x
    like task
      take k, like integer
      take p, like integer
      like integer
  mark e
    like task
      take t, like integer
      like integer
  mark m, like integer
  mark n, like integer
  have the-modulus-is-positive
    mark t, like integer
    meet or
      call is-below
        read t
        code 1
      call is-above
        call e
          read t
        code 0
  have the-modulus-quarters
    mark t, like integer
    meet or
      call is-below
        read t
        code 1
      call is-equal
        call multiply
          code 4
          call e
            call multiply
              code 4
              read t
        call e
          read t
  have each-is-a-real
    mark k, like integer
    mark p, like integer
    mark q, like integer
    meet or
      call is-below
        read k
        code 1
      call is-below
        read p
        code 1
      call is-below
        read q
        code 1
      meet and
        call is-maximum
          call subtract
            call x
              read k
              read p
            call x
              read k
              read q
          call add
            call e
              read p
            call e
              read q
        call is-maximum
          call subtract
            call x
              read k
              read q
            call x
              read k
              read p
          call add
            call e
              read p
            call e
              read q
  have they-are-a-cauchy-sequence
    mark k, like integer
    mark j, like integer
    mark p, like integer
    meet or
      call is-below
        read k
        code 1
      call is-below
        read j
        code 1
      call is-below
        read p
        code 1
      meet and
        call is-maximum
          call subtract
            call x
              read k
              read p
            call x
              read j
              read p
          call add
            call add
              call e
                read k
              call e
                read j
            call multiply
              code 2
              call e
                read p
        call is-maximum
          call subtract
            call x
              read j
              read p
            call x
              read k
              read p
          call add
            call add
              call e
                read k
              call e
                read j
            call multiply
              code 2
              call e
                read p
  have m-is-an-index
    call is-minimum
      read m
      code 1
  have n-is-an-index
    call is-minimum
      read n
      code 1
  show hold
    meet and
      call is-maximum
        call subtract
          call x
            call multiply
              code 4
              read m
            call multiply
              code 4
              read m
          call x
            call multiply
              code 4
              read n
            call multiply
              code 4
              read n
        call add
          call e
            read m
          call e
            read n
      call is-maximum
        call subtract
          call x
            call multiply
              code 4
              read n
            call multiply
              code 4
              read n
          call x
            call multiply
              code 4
              read m
            call multiply
              code 4
              read m
        call add
          call e
            read m
          call e
            read n
`,
  'ok',
)

expect(
  'the sequence converges to its limit',
  `
rule the-sequence-converges-to-its-limit
  mark x
    like task
      take k, like integer
      take p, like integer
      like integer
  mark e
    like task
      take t, like integer
      like integer
  mark k, like integer
  mark p, like integer
  have the-modulus-is-positive
    mark t, like integer
    meet or
      call is-below
        read t
        code 1
      call is-above
        call e
          read t
        code 0
  have the-modulus-quarters
    mark t, like integer
    meet or
      call is-below
        read t
        code 1
      call is-equal
        call multiply
          code 4
          call e
            call multiply
              code 4
              read t
        call e
          read t
  have each-is-a-real
    mark k, like integer
    mark p, like integer
    mark q, like integer
    meet or
      call is-below
        read k
        code 1
      call is-below
        read p
        code 1
      call is-below
        read q
        code 1
      meet and
        call is-maximum
          call subtract
            call x
              read k
              read p
            call x
              read k
              read q
          call add
            call e
              read p
            call e
              read q
        call is-maximum
          call subtract
            call x
              read k
              read q
            call x
              read k
              read p
          call add
            call e
              read p
            call e
              read q
  have they-are-a-cauchy-sequence
    mark k, like integer
    mark j, like integer
    mark p, like integer
    meet or
      call is-below
        read k
        code 1
      call is-below
        read j
        code 1
      call is-below
        read p
        code 1
      meet and
        call is-maximum
          call subtract
            call x
              read k
              read p
            call x
              read j
              read p
          call add
            call add
              call e
                read k
              call e
                read j
            call multiply
              code 2
              call e
                read p
        call is-maximum
          call subtract
            call x
              read j
              read p
            call x
              read k
              read p
          call add
            call add
              call e
                read k
              call e
                read j
            call multiply
              code 2
              call e
                read p
  have k-is-an-index
    call is-minimum
      read k
      code 1
  have p-is-an-index
    call is-minimum
      read p
      code 1
  show hold
    meet and
      call is-maximum
        call subtract
          call x
            read k
            read p
          call x
            call multiply
              code 4
              read p
            call multiply
              code 4
              read p
        call add
          call e
            read k
          call multiply
            code 2
            call e
              read p
      call is-maximum
        call subtract
          call x
            call multiply
              code 4
              read p
            call multiply
              code 4
              read p
          call x
            read k
            read p
        call add
          call e
            read k
          call multiply
            code 2
            call e
              read p
`,
  'ok',
)

expect(
  'a tighter limit is refused',
  `
rule control-a-tighter-limit
  mark x
    like task
      take k, like integer
      take p, like integer
      like integer
  mark e
    like task
      take t, like integer
      like integer
  mark m, like integer
  mark n, like integer
  have the-modulus-is-positive
    mark t, like integer
    meet or
      call is-below
        read t
        code 1
      call is-above
        call e
          read t
        code 0
  have the-modulus-quarters
    mark t, like integer
    meet or
      call is-below
        read t
        code 1
      call is-equal
        call multiply
          code 4
          call e
            call multiply
              code 4
              read t
        call e
          read t
  have each-is-a-real
    mark k, like integer
    mark p, like integer
    mark q, like integer
    meet or
      call is-below
        read k
        code 1
      call is-below
        read p
        code 1
      call is-below
        read q
        code 1
      meet and
        call is-maximum
          call subtract
            call x
              read k
              read p
            call x
              read k
              read q
          call add
            call e
              read p
            call e
              read q
        call is-maximum
          call subtract
            call x
              read k
              read q
            call x
              read k
              read p
          call add
            call e
              read p
            call e
              read q
  have they-are-a-cauchy-sequence
    mark k, like integer
    mark j, like integer
    mark p, like integer
    meet or
      call is-below
        read k
        code 1
      call is-below
        read j
        code 1
      call is-below
        read p
        code 1
      meet and
        call is-maximum
          call subtract
            call x
              read k
              read p
            call x
              read j
              read p
          call add
            call add
              call e
                read k
              call e
                read j
            call multiply
              code 2
              call e
                read p
        call is-maximum
          call subtract
            call x
              read j
              read p
            call x
              read k
              read p
          call add
            call add
              call e
                read k
              call e
                read j
            call multiply
              code 2
              call e
                read p
  have m-is-an-index
    call is-minimum
      read m
      code 1
  have n-is-an-index
    call is-minimum
      read n
      code 1
  show hold
    call is-maximum
      call subtract
        call x
          call multiply
            code 4
            read m
          call multiply
            code 4
            read m
        call x
          call multiply
            code 4
            read n
          call multiply
            code 4
            read n
      call e
        read m
`,
  'unproven',
)

expect(
  'the limit without the Cauchy hypothesis is refused',
  `
rule control-without-cauchy
  mark x
    like task
      take k, like integer
      take p, like integer
      like integer
  mark e
    like task
      take t, like integer
      like integer
  mark m, like integer
  mark n, like integer
  have the-modulus-is-positive
    mark t, like integer
    meet or
      call is-below
        read t
        code 1
      call is-above
        call e
          read t
        code 0
  have the-modulus-quarters
    mark t, like integer
    meet or
      call is-below
        read t
        code 1
      call is-equal
        call multiply
          code 4
          call e
            call multiply
              code 4
              read t
        call e
          read t
  have each-is-a-real
    mark k, like integer
    mark p, like integer
    mark q, like integer
    meet or
      call is-below
        read k
        code 1
      call is-below
        read p
        code 1
      call is-below
        read q
        code 1
      meet and
        call is-maximum
          call subtract
            call x
              read k
              read p
            call x
              read k
              read q
          call add
            call e
              read p
            call e
              read q
        call is-maximum
          call subtract
            call x
              read k
              read q
            call x
              read k
              read p
          call add
            call e
              read p
            call e
              read q
  have m-is-an-index
    call is-minimum
      read m
      code 1
  have n-is-an-index
    call is-minimum
      read n
      code 1
  show hold
    call is-maximum
      call subtract
        call x
          call multiply
            code 4
            read m
          call multiply
            code 4
            read m
        call x
          call multiply
            code 4
            read n
          call multiply
            code 4
            read n
      call add
        call e
          read m
        call e
          read n
`,
  'unproven',
)

expect(
  'a tighter convergence is refused',
  `
rule control-a-tighter-convergence
  mark x
    like task
      take k, like integer
      take p, like integer
      like integer
  mark e
    like task
      take t, like integer
      like integer
  mark k, like integer
  mark p, like integer
  have the-modulus-is-positive
    mark t, like integer
    meet or
      call is-below
        read t
        code 1
      call is-above
        call e
          read t
        code 0
  have the-modulus-quarters
    mark t, like integer
    meet or
      call is-below
        read t
        code 1
      call is-equal
        call multiply
          code 4
          call e
            call multiply
              code 4
              read t
        call e
          read t
  have each-is-a-real
    mark k, like integer
    mark p, like integer
    mark q, like integer
    meet or
      call is-below
        read k
        code 1
      call is-below
        read p
        code 1
      call is-below
        read q
        code 1
      meet and
        call is-maximum
          call subtract
            call x
              read k
              read p
            call x
              read k
              read q
          call add
            call e
              read p
            call e
              read q
        call is-maximum
          call subtract
            call x
              read k
              read q
            call x
              read k
              read p
          call add
            call e
              read p
            call e
              read q
  have they-are-a-cauchy-sequence
    mark k, like integer
    mark j, like integer
    mark p, like integer
    meet or
      call is-below
        read k
        code 1
      call is-below
        read j
        code 1
      call is-below
        read p
        code 1
      meet and
        call is-maximum
          call subtract
            call x
              read k
              read p
            call x
              read j
              read p
          call add
            call add
              call e
                read k
              call e
                read j
            call multiply
              code 2
              call e
                read p
        call is-maximum
          call subtract
            call x
              read j
              read p
            call x
              read k
              read p
          call add
            call add
              call e
                read k
              call e
                read j
            call multiply
              code 2
              call e
                read p
  have k-is-an-index
    call is-minimum
      read k
      code 1
  have p-is-an-index
    call is-minimum
      read p
      code 1
  show hold
    call is-maximum
      call subtract
        call x
          read k
          read p
        call x
          call multiply
            code 4
            read p
          call multiply
            code 4
            read p
      call add
        call e
          read k
        call e
          read p
`,
  'unproven',
)

expect(
  'the fundamental theorem of calculus, for Riemann sums',
  `
rule the-riemann-sums-of-a-derivative-approach-its-difference
  mark bigf
    like task
      take a0, like integer
      like integer
  mark f
    like task
      take a0, like integer
      like integer
  mark pt
    like task
      take a0, like integer
      like integer
  mark sum
    like task
      take a0, like integer
      like integer
  mark n, like integer
  mark w, like integer
  mark eps, like integer
  have the-points-are-evenly-spaced
    mark i, like integer
    meet or
      call is-below
        read i
        code 0
      call is-equal
        call subtract
          call pt
            call add
              read i
              code 1
          call pt
            read i
        read w
  have bigf-has-derivative-f-at-the-mesh
    mark i, like integer
    meet or
      call is-below
        read i
        code 0
      meet and
        call is-maximum
          call subtract
            call subtract
              call bigf
                call pt
                  call add
                    read i
                    code 1
              call bigf
                call pt
                  read i
            call multiply
              call f
                call pt
                  read i
              read w
          call multiply
            read eps
            read w
        call is-maximum
          call subtract
            call multiply
              call f
                call pt
                  read i
              read w
            call subtract
              call bigf
                call pt
                  call add
                    read i
                    code 1
              call bigf
                call pt
                  read i
          call multiply
            read eps
            read w
  have the-riemann-sum-starts-at-zero
    call is-equal
      call sum
        code 0
      code 0
  have the-riemann-sum-adds-a-strip
    mark i, like integer
    meet or
      call is-below
        read i
        code 0
      call is-equal
        call sum
          call add
            read i
            code 1
        call add
          call sum
            read i
          call multiply
            call f
              call pt
                read i
            read w
  have the-width-is-positive
    call is-above
      read w
      code 0
  have the-tolerance-is-not-negative
    call is-minimum
      read eps
      code 0
  have n-is-a-count
    call is-minimum
      read n
      code 0
  show hold
    meet and
      call is-maximum
        call subtract
          call sum
            read n
          call subtract
            call bigf
              call pt
                read n
            call bigf
              call pt
                code 0
        call multiply
          call multiply
            read eps
            read n
          read w
      call is-maximum
        call subtract
          call subtract
            call bigf
              call pt
                read n
            call bigf
              call pt
                code 0
          call sum
            read n
        call multiply
          call multiply
            read eps
            read n
          read w
  fold n
`,
  'ok',
)

expect(
  'the disk area sum telescopes',
  `
rule the-disk-area-sum-telescopes
  mark cc
    like task
      take a0, like integer
      like integer
  mark mid
    like task
      take a0, like integer
      like integer
  mark acc
    like task
      take a0, like integer
      like integer
  mark n, like integer
  mark s, like integer
  have each-strip-is-a-difference
    mark i, like integer
    meet or
      call is-below
        read i
        code 0
      call is-equal
        call subtract
          call cc
            call add
              read i
              code 1
          call cc
            read i
        call multiply
          call multiply
            code 2
            read s
          call mid
            read i
  have the-sum-starts-at-zero
    call is-equal
      call acc
        code 0
      code 0
  have the-sum-adds-a-strip
    mark i, like integer
    meet or
      call is-below
        read i
        code 0
      call is-equal
        call acc
          call add
            read i
            code 1
        call add
          call acc
            read i
          call multiply
            call multiply
              code 2
              read s
            call mid
              read i
  have n-is-a-count
    call is-minimum
      read n
      code 0
  show hold
    call is-equal
      call acc
        read n
      call subtract
        call cc
          read n
        call cc
          code 0
  fold n
`,
  'ok',
)

expect(
  'cosh has derivative sinh',
  `
rule cosh-has-derivative-sinh
  mark cc
    like task
      take a0, like integer
      like integer
  mark ss
    like task
      take a0, like integer
      like integer
  mark x, like integer
  mark w, like integer
  mark big, like integer
  have the-addition-formula
    mark a, like integer
    mark b, like integer
    call is-equal
      call cc
        call add
          read a
          read b
      call add
        call multiply
          call cc
            read a
          call cc
            read b
        call multiply
          call ss
            read a
          call ss
            read b
  have cosh-near-zero
    mark u, like integer
    meet or
      call is-below
        read u
        code 0
      call is-above
        read u
        code 1
      meet and
        call is-minimum
          call subtract
            call cc
              read u
            code 1
          code 0
        call is-maximum
          call subtract
            call cc
              read u
            code 1
          call multiply
            read u
            read u
  have sinh-near-zero
    mark u, like integer
    meet or
      call is-below
        read u
        code 0
      call is-above
        read u
        code 1
      meet and
        call is-minimum
          call subtract
            call ss
              read u
            read u
          code 0
        call is-maximum
          call subtract
            call ss
              read u
            read u
          call multiply
            call multiply
              read u
              read u
            read u
  have the-step-is-small
    meet and
      call is-minimum
        read w
        code 0
      call is-maximum
        read w
        code 1
  have cosh-is-bounded-here
    meet and
      call is-minimum
        call cc
          read x
        code 0
      call is-maximum
        call cc
          read x
        read big
  have sinh-is-bounded-here
    meet and
      call is-minimum
        call ss
          read x
        code 0
      call is-maximum
        call ss
          read x
        read big
  have the-bound-is-not-negative
    call is-minimum
      read big
      code 0
  show hold
    meet and
      call is-maximum
        call subtract
          call subtract
            call cc
              call add
                read x
                read w
            call cc
              read x
          call multiply
            call ss
              read x
            read w
        call add
          call multiply
            call multiply
              read big
              read w
            read w
          call multiply
            call multiply
              call multiply
                read big
                read w
              read w
            read w
      call is-minimum
        call subtract
          call subtract
            call cc
              call add
                read x
                read w
            call cc
              read x
          call multiply
            call ss
              read x
            read w
        code 0
`,
  'ok',
)

expect(
  'area equals defect (Gauss-Bonnet)',
  `
rule area-equals-defect
  mark ar
    like task
      take a0, like integer
      like integer
  mark ps
    like task
      take a0, like integer
      like integer
  mark th
    like task
      take a0, like integer
      like integer
  mark c
    like task
      take a0, like integer
      like integer
  mark ia
    like task
      take a0, like integer
      like integer
  mark ip
    like task
      take a0, like integer
      like integer
  mark it
    like task
      take a0, like integer
      like integer
  mark n, like integer
  mark w, like integer
  mark eps, like integer
  have the-area-follows-its-increment
    mark i, like integer
    meet or
      call is-below
        read i
        code 0
      meet and
        call is-maximum
          call subtract
            call subtract
              call ar
                call add
                  read i
                  code 1
              call ar
                read i
            call ia
              read i
          call multiply
            read eps
            read w
        call is-maximum
          call subtract
            call ia
              read i
            call subtract
              call ar
                call add
                  read i
                  code 1
              call ar
                read i
          call multiply
            read eps
            read w
  have psi-follows-its-increment
    mark i, like integer
    meet or
      call is-below
        read i
        code 0
      meet and
        call is-maximum
          call subtract
            call subtract
              call ps
                call add
                  read i
                  code 1
              call ps
                read i
            call ip
              read i
          call multiply
            read eps
            read w
        call is-maximum
          call subtract
            call ip
              read i
            call subtract
              call ps
                call add
                  read i
                  code 1
              call ps
                read i
          call multiply
            read eps
            read w
  have theta-follows-its-increment
    mark i, like integer
    meet or
      call is-below
        read i
        code 0
      meet and
        call is-maximum
          call subtract
            call subtract
              call th
                call add
                  read i
                  code 1
              call th
                read i
            call it
              read i
          call multiply
            read eps
            read w
        call is-maximum
          call subtract
            call it
              read i
            call subtract
              call th
                call add
                  read i
                  code 1
              call th
                read i
          call multiply
            read eps
            read w
  have the-area-element
    mark i, like integer
    meet or
      call is-below
        read i
        code 0
      call is-equal
        call ia
          read i
        call subtract
          call multiply
            call c
              read i
            call it
              read i
          call it
            read i
  have the-turning
    mark i, like integer
    meet or
      call is-below
        read i
        code 0
      call is-equal
        call ip
          read i
        call subtract
          code 0
          call multiply
            call c
              read i
            call it
              read i
  have the-width-is-positive
    call is-above
      read w
      code 0
  have the-tolerance-is-not-negative
    call is-minimum
      read eps
      code 0
  have n-is-a-count
    call is-minimum
      read n
      code 0
  show hold
    meet and
      call is-maximum
        call add
          call add
            call subtract
              call ar
                read n
              call ar
                code 0
            call subtract
              call ps
                read n
              call ps
                code 0
          call subtract
            call th
              read n
            call th
              code 0
        call multiply
          call multiply
            call multiply
              code 3
              read eps
            read n
          read w
      call is-maximum
        call subtract
          code 0
          call add
            call add
              call subtract
                call ar
                  read n
                call ar
                  code 0
              call subtract
                call ps
                  read n
                call ps
                  code 0
            call subtract
              call th
                read n
              call th
                code 0
        call multiply
          call multiply
            call multiply
              code 3
              read eps
            read n
          read w
  fold n
`,
  'ok',
)

expect(
  'half the tolerance is refused',
  `
rule control-half-the-tolerance
  mark bigf
    like task
      take a0, like integer
      like integer
  mark f
    like task
      take a0, like integer
      like integer
  mark pt
    like task
      take a0, like integer
      like integer
  mark sum
    like task
      take a0, like integer
      like integer
  mark n, like integer
  mark w, like integer
  mark eps, like integer
  have the-points-are-evenly-spaced
    mark i, like integer
    meet or
      call is-below
        read i
        code 0
      call is-equal
        call subtract
          call pt
            call add
              read i
              code 1
          call pt
            read i
        read w
  have bigf-has-derivative-f-at-the-mesh
    mark i, like integer
    meet or
      call is-below
        read i
        code 0
      meet and
        call is-maximum
          call subtract
            call subtract
              call bigf
                call pt
                  call add
                    read i
                    code 1
              call bigf
                call pt
                  read i
            call multiply
              call f
                call pt
                  read i
              read w
          call multiply
            read eps
            read w
        call is-maximum
          call subtract
            call multiply
              call f
                call pt
                  read i
              read w
            call subtract
              call bigf
                call pt
                  call add
                    read i
                    code 1
              call bigf
                call pt
                  read i
          call multiply
            read eps
            read w
  have the-riemann-sum-starts-at-zero
    call is-equal
      call sum
        code 0
      code 0
  have the-riemann-sum-adds-a-strip
    mark i, like integer
    meet or
      call is-below
        read i
        code 0
      call is-equal
        call sum
          call add
            read i
            code 1
        call add
          call sum
            read i
          call multiply
            call f
              call pt
                read i
            read w
  have the-width-is-positive
    call is-above
      read w
      code 0
  have the-tolerance-is-not-negative
    call is-minimum
      read eps
      code 0
  have n-is-a-count
    call is-minimum
      read n
      code 0
  show hold
    call is-maximum
      call subtract
        call sum
          read n
        call subtract
          call bigf
            call pt
              read n
          call bigf
            call pt
              code 0
      call subtract
        call multiply
          call multiply
            read eps
            read n
          read w
        call multiply
          read eps
          read w
  fold n
`,
  'unproven',
)

expect(
  'the sum without the derivative is refused',
  `
rule control-without-the-derivative
  mark bigf
    like task
      take a0, like integer
      like integer
  mark f
    like task
      take a0, like integer
      like integer
  mark pt
    like task
      take a0, like integer
      like integer
  mark sum
    like task
      take a0, like integer
      like integer
  mark n, like integer
  mark w, like integer
  mark eps, like integer
  have the-points-are-evenly-spaced
    mark i, like integer
    meet or
      call is-below
        read i
        code 0
      call is-equal
        call subtract
          call pt
            call add
              read i
              code 1
          call pt
            read i
        read w
  have the-riemann-sum-starts-at-zero
    call is-equal
      call sum
        code 0
      code 0
  have the-riemann-sum-adds-a-strip
    mark i, like integer
    meet or
      call is-below
        read i
        code 0
      call is-equal
        call sum
          call add
            read i
            code 1
        call add
          call sum
            read i
          call multiply
            call f
              call pt
                read i
            read w
  have the-width-is-positive
    call is-above
      read w
      code 0
  have the-tolerance-is-not-negative
    call is-minimum
      read eps
      code 0
  have n-is-a-count
    call is-minimum
      read n
      code 0
  show hold
    call is-maximum
      call subtract
        call sum
          read n
        call subtract
          call bigf
            call pt
              read n
          call bigf
            call pt
              code 0
      call multiply
        call multiply
          read eps
          read n
        read w
  fold n
`,
  'unproven',
)

expect(
  'a nonlinear hypothesis is assumed as stated, never as its negation',
  `
rule control-a-two-sided-nonlinear-hypothesis
  mark x
    like task
      take a0, like integer
      like integer
  mark y, like integer
  have bounded
    mark t, like integer
    meet and
      call is-maximum
        call multiply
          call x
            read t
          read y
        code 1
      call is-minimum
        call multiply
          call x
            read t
          read y
        code 0
  show hold
    call is-minimum
      call multiply
        call x
          code 0
        read y
      code 7
`,
  'unproven',
)

expect(
  'the telescoped sum off by one is refused',
  `
rule control-the-disk-sum-off-by-one
  mark cc
    like task
      take a0, like integer
      like integer
  mark mid
    like task
      take a0, like integer
      like integer
  mark acc
    like task
      take a0, like integer
      like integer
  mark n, like integer
  mark s, like integer
  have each-strip-is-a-difference
    mark i, like integer
    meet or
      call is-below
        read i
        code 0
      call is-equal
        call subtract
          call cc
            call add
              read i
              code 1
          call cc
            read i
        call multiply
          call multiply
            code 2
            read s
          call mid
            read i
  have the-sum-starts-at-zero
    call is-equal
      call acc
        code 0
      code 0
  have the-sum-adds-a-strip
    mark i, like integer
    meet or
      call is-below
        read i
        code 0
      call is-equal
        call acc
          call add
            read i
            code 1
        call add
          call acc
            read i
          call multiply
            call multiply
              code 2
              read s
            call mid
              read i
  have n-is-a-count
    call is-minimum
      read n
      code 0
  show hold
    call is-equal
      call acc
        read n
      call cc
        read n
  fold n
`,
  'unproven',
)

expect(
  'cosh without the cube term is refused',
  `
rule control-cosh-without-the-cube
  mark cc
    like task
      take a0, like integer
      like integer
  mark ss
    like task
      take a0, like integer
      like integer
  mark x, like integer
  mark w, like integer
  mark big, like integer
  have the-addition-formula
    mark a, like integer
    mark b, like integer
    call is-equal
      call cc
        call add
          read a
          read b
      call add
        call multiply
          call cc
            read a
          call cc
            read b
        call multiply
          call ss
            read a
          call ss
            read b
  have cosh-near-zero
    mark u, like integer
    meet or
      call is-below
        read u
        code 0
      call is-above
        read u
        code 1
      meet and
        call is-minimum
          call subtract
            call cc
              read u
            code 1
          code 0
        call is-maximum
          call subtract
            call cc
              read u
            code 1
          call multiply
            read u
            read u
  have sinh-near-zero
    mark u, like integer
    meet or
      call is-below
        read u
        code 0
      call is-above
        read u
        code 1
      meet and
        call is-minimum
          call subtract
            call ss
              read u
            read u
          code 0
        call is-maximum
          call subtract
            call ss
              read u
            read u
          call multiply
            call multiply
              read u
              read u
            read u
  have the-step-is-small
    meet and
      call is-minimum
        read w
        code 0
      call is-maximum
        read w
        code 1
  have cosh-is-bounded-here
    meet and
      call is-minimum
        call cc
          read x
        code 0
      call is-maximum
        call cc
          read x
        read big
  have sinh-is-bounded-here
    meet and
      call is-minimum
        call ss
          read x
        code 0
      call is-maximum
        call ss
          read x
        read big
  have the-bound-is-not-negative
    call is-minimum
      read big
      code 0
  show hold
    call is-maximum
      call subtract
        call subtract
          call cc
            call add
              read x
              read w
          call cc
            read x
        call multiply
          call ss
            read x
          read w
      call multiply
        call multiply
          read big
          read w
        read w
`,
  'unproven',
)

expect(
  'Gauss-Bonnet without the turning identity is refused',
  `
rule control-gauss-bonnet-without-the-turning
  mark ar
    like task
      take a0, like integer
      like integer
  mark ps
    like task
      take a0, like integer
      like integer
  mark th
    like task
      take a0, like integer
      like integer
  mark c
    like task
      take a0, like integer
      like integer
  mark ia
    like task
      take a0, like integer
      like integer
  mark ip
    like task
      take a0, like integer
      like integer
  mark it
    like task
      take a0, like integer
      like integer
  mark n, like integer
  mark w, like integer
  mark eps, like integer
  have the-area-follows-its-increment
    mark i, like integer
    meet or
      call is-below
        read i
        code 0
      meet and
        call is-maximum
          call subtract
            call subtract
              call ar
                call add
                  read i
                  code 1
              call ar
                read i
            call ia
              read i
          call multiply
            read eps
            read w
        call is-maximum
          call subtract
            call ia
              read i
            call subtract
              call ar
                call add
                  read i
                  code 1
              call ar
                read i
          call multiply
            read eps
            read w
  have psi-follows-its-increment
    mark i, like integer
    meet or
      call is-below
        read i
        code 0
      meet and
        call is-maximum
          call subtract
            call subtract
              call ps
                call add
                  read i
                  code 1
              call ps
                read i
            call ip
              read i
          call multiply
            read eps
            read w
        call is-maximum
          call subtract
            call ip
              read i
            call subtract
              call ps
                call add
                  read i
                  code 1
              call ps
                read i
          call multiply
            read eps
            read w
  have theta-follows-its-increment
    mark i, like integer
    meet or
      call is-below
        read i
        code 0
      meet and
        call is-maximum
          call subtract
            call subtract
              call th
                call add
                  read i
                  code 1
              call th
                read i
            call it
              read i
          call multiply
            read eps
            read w
        call is-maximum
          call subtract
            call it
              read i
            call subtract
              call th
                call add
                  read i
                  code 1
              call th
                read i
          call multiply
            read eps
            read w
  have the-area-element
    mark i, like integer
    meet or
      call is-below
        read i
        code 0
      call is-equal
        call ia
          read i
        call subtract
          call multiply
            call c
              read i
            call it
              read i
          call it
            read i
  have the-width-is-positive
    call is-above
      read w
      code 0
  have the-tolerance-is-not-negative
    call is-minimum
      read eps
      code 0
  have n-is-a-count
    call is-minimum
      read n
      code 0
  show hold
    meet and
      call is-maximum
        call add
          call add
            call subtract
              call ar
                read n
              call ar
                code 0
            call subtract
              call ps
                read n
              call ps
                code 0
          call subtract
            call th
              read n
            call th
              code 0
        call multiply
          call multiply
            call multiply
              code 3
              read eps
            read n
          read w
      call is-maximum
        call subtract
          code 0
          call add
            call add
              call subtract
                call ar
                  read n
                call ar
                  code 0
              call subtract
                call ps
                  read n
                call ps
                  code 0
            call subtract
              call th
                read n
              call th
                code 0
        call multiply
          call multiply
            call multiply
              code 3
              read eps
            read n
          read w
  fold n
`,
  'unproven',
)

console.log(`\nuniversal: ${pass} pass, ${fail} fail`)

if (fail > 0) {
  process.exit(1)
}
