object fmath {
    fun sqrt(v: Double): Double = kotlin.math.sqrt(v)
    fun floor(v: Double): Double = kotlin.math.floor(v)
    fun ceil(v: Double): Double = kotlin.math.ceil(v)
    fun round(v: Double): Double = kotlin.math.round(v)
    fun pow(base: Double, exponent: Double): Double = Math.pow(base, exponent)
    fun abs(v: Double): Double = kotlin.math.abs(v)
    fun sin(v: Double): Double = kotlin.math.sin(v)
    fun cos(v: Double): Double = kotlin.math.cos(v)
    fun tan(v: Double): Double = kotlin.math.tan(v)
    fun asin(v: Double): Double = kotlin.math.asin(v)
    fun acos(v: Double): Double = kotlin.math.acos(v)
    fun atan(v: Double): Double = kotlin.math.atan(v)
    fun atan2(y: Double, x: Double): Double = kotlin.math.atan2(y, x)
}
