// GENERATED by the asset sync task. Do not edit.
//
// Self-contained runtime shim for the site-asset manifest, the Term (`@term/site`) analog of the React
// the React site-asset accessor build-time accessor. Provided to Seed via <global:asset> (docked
// `name asset`, so this object IS the binding); the `.tree` accessor (../asset.tree) calls `asset/get` /
// `asset/try-get` / `asset/entry`. A namespace object (not top-level functions) so the bundled client has no
// name collisions, matching the resize / fontset / title runtimes.
//
// Why the manifest is EMBEDDED here rather than `import`ed from ./assets.json (as the React asset.ts does):
// the production Cloudflare cast concatenates this shim's raw source as a prelude in front of the compiled app
// (see deck/make.tree native prelude), so a relative `import` would not resolve from the bundle's location. The
// manifest is inlined instead. This is the ONLY difference from asset.ts; the API + behavior (throw-vs-null,
// the manifest shape) are identical. assets.json stays the canonical data file that sync change-detects against;
// this snapshot is regenerated from it on every sync.
//
// Spec: note/platform/infrastructure/site-asset-sync.md

/**
 * Tone-encoded UUID minted via `makeId()` when this version was first published (`code`), the tone-encoded
 * SHA-256 fingerprint of the body (`hash`, change-detection only), the byte length (`size`), and the current
 * hashed URL on `site.clue.surf` (`link`). Runtime consumers should rely on `link`.
 */
export type AssetEntry = {
  code: string
  hash: string
  size: number
  link: string
}

export type AssetsManifest = {
  version: number
  generated_at: string
  host: string
  assets: Record<string, AssetEntry>
}

// The bundled manifest snapshot (regenerated from ./assets.json on every sync).
const MANIFEST: AssetsManifest = {
  "version": 1,
  "generated_at": "2026-07-09T09:47:37.636Z",
  "host": "https://site.clue.surf",
  "assets": {
    "/CrowMark.otf": {
      "code": "rwvs-wdbh-cvnm-tncf-xztc-chfr-thhc-lnfz",
      "hash": "kmhzssvdcsffkvfsktrvnrmczswkmmvxvhrxslvtdznlfknbwdvxlfdtszvdmhcs",
      "size": 265856,
      "link": "https://site.clue.surf/rwvs-wdbh-cvnm-tncf-xztc-chfr-thhc-lnfz.otf"
    },
    "/apple-touch-icon.png": {
      "code": "rlcl-kksk-mfvm-tlzn-zmms-lmww-vvxr-bbcv",
      "hash": "ksmhsxnrvmtdfvllzvdvkvdrnhhlstxtlkhnvzbzbrmzmkrhmlmlrcvttfdxndlk",
      "size": 10400,
      "link": "https://site.clue.surf/rlcl-kksk-mfvm-tlzn-zmms-lmww-vvxr-bbcv.png"
    },
    "/axe.png": {
      "code": "cxzz-fdtb-wcnv-tsmf-xbnd-sbkc-srvl-mwml",
      "hash": "mvrncbwlklzxrmhkcnxzbhfwlwfxfmtnvtlhfmvbxwbxlmctdzmrlshltmdvrzht",
      "size": 386407,
      "link": "https://site.clue.surf/cxzz-fdtb-wcnv-tsmf-xbnd-sbkc-srvl-mwml.png"
    },
    "/beat.png": {
      "code": "dnwz-hmts-nrmn-tlzb-fxsw-mlcz-mvwt-fttk",
      "hash": "vrzlndfrrthlfzmtfsmkscfwsdmmhxhxbscsvwdmhmzmmszctdbblzrkbcsbmfdb",
      "size": 416341,
      "link": "https://site.clue.surf/dnwz-hmts-nrmn-tlzb-fxsw-mlcz-mvwt-fttk.png"
    },
    "/bush.svg": {
      "code": "nbdw-mbdv-tnlh-thbw-frnd-wshz-zshz-csrd",
      "hash": "mfchbvhntvtkwtlnbbtknsncmfnkcrfhwnwxnnzclklszkxcnmbnmwckmzthzmcx",
      "size": 991702,
      "link": "https://site.clue.surf/nbdw-mbdv-tnlh-thbw-frnd-wshz-zshz-csrd.svg"
    },
    "/cdn-test.txt": {
      "code": "bhxf-tddw-vwth-thmr-zkrz-lvts-zxkc-mxrl",
      "hash": "xkhcfzbsdhkzmrbfthlnxzmkwsrztcdwdmckhkvlltrlzcmdzncclmbwxwdwtmxd",
      "size": 11,
      "link": "https://site.clue.surf/bhxf-tddw-vwth-thmr-zkrz-lvts-zxkc-mxrl.txt"
    },
    "/chisel.png": {
      "code": "hkzc-vbrc-cchz-tvcm-ztnb-sfvv-mzwb-zbrk",
      "hash": "mrfkrwmvnrhlcxrvmbvxtxtnrdbwfzwtsxxfswvvhtwdhfknlnzkhnvzwfzrtvwh",
      "size": 291813,
      "link": "https://site.clue.surf/hkzc-vbrc-cchz-tvcm-ztnb-sfvv-mzwb-zbrk.png"
    },
    "/controlled-fire.png": {
      "code": "fmvs-xkmc-cftr-tswc-xxfh-vflr-vcxz-hlzv",
      "hash": "llkzbxshxhtnsndmznflwcfmctcwknmbfvrfrvbtdwrtcmwcvbztvzfclzhmzflb",
      "size": 445699,
      "link": "https://site.clue.surf/fmvs-xkmc-cftr-tswc-xxfh-vflr-vcxz-hlzv.png"
    },
    "/drum.png": {
      "code": "strc-tznw-nkmt-trml-vmnw-nwdt-vvmf-tkzv",
      "hash": "fxmvzlvfdmvwlvmzdckxrlvkfvxxhhstzslhlkfkxmttsthzzkmwwlwclhkzkrhz",
      "size": 427047,
      "link": "https://site.clue.surf/strc-tznw-nkmt-trml-vmnw-nwdt-vvmf-tkzv.png"
    },
    "/earthbump1k.jpg": {
      "code": "wtkz-ntrv-fdth-tkcr-fmzk-lbdm-vxnw-tbns",
      "hash": "xhwsvnxzvrmnszfhswlhhdvlllzdvwktvblbwmzvbfnvvvthhshlnmshmcnhtzcs",
      "size": 91237,
      "link": "https://site.clue.surf/wtkz-ntrv-fdth-tkcr-fmzk-lbdm-vxnw-tbns.jpg"
    },
    "/earthcloudmaptrans.jpg": {
      "code": "vvwx-ttvb-wvbn-tssl-zsrl-shkt-wlxf-mwbk",
      "hash": "tnhmnswmntsbvzmhcnvdbrtzdltvnttswctkxcdwsfbzsbxbkwsmnfffcsnszhzw",
      "size": 184128,
      "link": "https://site.clue.surf/vvwx-ttvb-wvbn-tssl-zsrl-shkt-wlxf-mwbk.jpg"
    },
    "/favicon-16x16.png": {
      "code": "xlmc-kwvw-zrwc-tlbl-vsmn-btht-bcmf-csxh",
      "hash": "hnbnkcrstmdbmkzbvrlvrccxktcldswtddzbmwbfzcxsnhzhtdhhnfzzfrmzzntw",
      "size": 1804,
      "link": "https://site.clue.surf/xlmc-kwvw-zrwc-tlbl-vsmn-btht-bcmf-csxh.png"
    },
    "/favicon-32x32.png": {
      "code": "lrcm-mkdn-zfsh-tbnt-zhrk-sxrs-csrv-fbdl",
      "hash": "lhfsnknwhsmvdlkmzbfdhbcmtzzfblkfvfmnwxrfcrcxrbftttwmffrvbcvxlnbw",
      "size": 3362,
      "link": "https://site.clue.surf/lrcm-mkdn-zfsh-tbnt-zhrk-sxrs-csrv-fbdl.png"
    },
    "/favicon.ico": {
      "code": "nznh-flst-btsb-tblk-zrbz-shsd-kwxb-rlbd",
      "hash": "rhdtshxxlccbbzcrmhrckcrzhwtwvhkvccrhbnmtlmhvsrdmrhcwsctbthfxrvcb",
      "size": 15406,
      "link": "https://site.clue.surf/nznh-flst-btsb-tblk-zrbz-shsd-kwxb-rlbd.ico"
    },
    "/flame.gif": {
      "code": "zfdx-mtms-ldcx-tbhw-frlx-zwsc-mhvr-fftc",
      "hash": "mmnvkttlskvxlztbrhfstmdkkznbdbsklwsdlxcfsdvhzfnrhszmkxdmcrwltwnw",
      "size": 69275,
      "link": "https://site.clue.surf/zfdx-mtms-ldcx-tbhw-frlx-zwsc-mhvr-fftc.gif"
    },
    "/font.webp": {
      "code": "mfzc-zncc-csbf-tbsn-zztw-cxfk-mvzn-xdvk",
      "hash": "kcbdrxcstwsrtmnxmwbkwsfmdzlcdvkktfxvmrrxzdwtdtbsrhzlhrhcnnfzrrhz",
      "size": 237270,
      "link": "https://site.clue.surf/mfzc-zncc-csbf-tbsn-zztw-cxfk-mvzn-xdvk.webp"
    },
    "/keyboard.webp": {
      "code": "cbcv-wsrw-rffz-tvxr-fdxk-trtb-nztb-mwdh",
      "hash": "rhtsnzkhlkxnnxfxnlbfhdztrllhbwnrxrzbzrsvdcbtnvshsthsltxnxsxsmhxv",
      "size": 421892,
      "link": "https://site.clue.surf/cbcv-wsrw-rffz-tvxr-fdxk-trtb-nztb-mwdh.webp"
    },
    "/land.png": {
      "code": "mthk-xbdd-wkzc-tbwd-xxvs-wwth-hzkd-tkvr",
      "hash": "tcvsrrkcvtlfchxzndhtdlzcrmctmflfwtctzcdlzsdxwmxfrcfvvtfsvshcnftk",
      "size": 370067,
      "link": "https://site.clue.surf/mthk-xbdd-wkzc-tbwd-xxvs-wwth-hzkd-tkvr.png"
    },
    "/language.png": {
      "code": "trlv-brsm-xnkd-tlfb-fhzr-ncxn-sltb-fbvv",
      "hash": "nrhhcdhrtmmmxzwmnhxkcdkmtsbbfxzrcmkmdslxbbddtddnttfddmkbrktbrcsz",
      "size": 292526,
      "link": "https://site.clue.surf/trlv-brsm-xnkd-tlfb-fhzr-ncxn-sltb-fbvv.png"
    },
    "/language.webp": {
      "code": "tzvh-dxvn-wwrf-ttdk-vscd-fkrr-vhwx-bhdl",
      "hash": "sbsmdbwbzzncmhhrhcxtvnxshtdkcmzfsdmrknlmrvbhwtxkdlkhznvvnxrwzdwc",
      "size": 352730,
      "link": "https://site.clue.surf/tzvh-dxvn-wwrf-ttdk-vscd-fkrr-vhwx-bhdl.webp"
    },
    "/logo.png": {
      "code": "zskm-nlhn-bmwd-tmxh-ztzv-zsmd-vfzh-mbsm",
      "hash": "xhkmcmhsmnhnvslczvtdlvrcdhdnxxcvbtvhrxcwmfcktwtkxxvndbvkssxhlvkk",
      "size": 80882,
      "link": "https://site.clue.surf/zskm-nlhn-bmwd-tmxh-ztzv-zsmd-vfzh-mbsm.png"
    },
    "/monkey.png": {
      "code": "zmcx-nclk-fksl-tzsh-vfkb-kxck-clxh-whdh",
      "hash": "wmvdsfrfbkkztnzwbmknrkbkkhmkrdlzcknvhddldhvdmxrtrzvccszwkvszsrzd",
      "size": 207553,
      "link": "https://site.clue.surf/zmcx-nclk-fksl-tzsh-vfkb-kxck-clxh-whdh.png"
    },
    "/moon.svg": {
      "code": "vhww-mcmc-kzcb-trth-zlst-nxvm-clxz-vxmw",
      "hash": "zkrffxsxbhkhszfdkzvmxmwkbffkwrdzmvldnrlkxfnfmthvkkchnrzscczhxlch",
      "size": 1170481,
      "link": "https://site.clue.surf/vhww-mcmc-kzcb-trth-zlst-nxvm-clxz-vxmw.svg"
    },
    "/mountains.svg": {
      "code": "rzkw-rbdb-lvmr-tzwz-xkwt-wwzt-tcwn-rcth",
      "hash": "fwxrrvrxtvvxrmflxhnkbfzhdskwtmmzzwtmtxzmvzlfsccnkhzvrssthxxwkcbc",
      "size": 216346,
      "link": "https://site.clue.surf/rzkw-rbdb-lvmr-tzwz-xkwt-wwzt-tcwn-rcth.svg"
    },
    "/notation.png": {
      "code": "fltt-knkw-tzcd-tfbz-vvkb-tccx-czlt-mths",
      "hash": "kwkxlzsrfxzmlncmnxnzbhndthtxnwhlmxdwsnchvzvktrctkvdvwwshctbwnxzb",
      "size": 145059,
      "link": "https://site.clue.surf/fltt-knkw-tzcd-tfbz-vvkb-tccx-czlt-mths.png"
    },
    "/power-grip.png": {
      "code": "zhwt-bxbt-mndx-tvlr-vcnx-tcvz-vdzl-srdk",
      "hash": "cnbsdbcwzdbcxhnhzbcwfhwbncvhwlhmhmkccbbtscvlnrxxlwvtvttrzlxrzrbl",
      "size": 302435,
      "link": "https://site.clue.surf/zhwt-bxbt-mndx-tvlr-vcnx-tcvz-vdzl-srdk.png"
    },
    "/precision-grip.png": {
      "code": "cmkc-mzfm-ctnl-tsnv-fvvz-lrfn-twcz-dkzx",
      "hash": "xsbdvtfvctcmzdbltrcmkwdfvxrnkmndlsmnrtlmsvzbvnhvksrttcnckdmfbnls",
      "size": 234918,
      "link": "https://site.clue.surf/cmkc-mzfm-ctnl-tsnv-fvvz-lrfn-twcz-dkzx.png"
    },
    "/rattle.png": {
      "code": "smrr-nzsh-zzhk-tktm-zrtr-tlhc-rxtv-xkdf",
      "hash": "hvcsdnbtbrrmlnfzbfllmkxzbflrfnzkhlxhrlwtsxrwzhvlmmtrkchdffnxwvvf",
      "size": 314294,
      "link": "https://site.clue.surf/smrr-nzsh-zzhk-tktm-zrtr-tlhc-rxtv-xkdf.png"
    },
    "/script.webp": {
      "code": "cswb-kcnr-dvtv-thxr-xxvb-hvkt-bntk-bzvf",
      "hash": "lthbdlsfhnxdsfwrldkwmmxdlbkfbcsdmntwtcmmtwfhtzmczvzbrtltkfbwdrrc",
      "size": 261366,
      "link": "https://site.clue.surf/cswb-kcnr-dvtv-thxr-xxvb-hvkt-bntk-bzvf.webp"
    },
    "/sound.webp": {
      "code": "xbbl-dbzk-wrdz-tknz-zwmw-bzct-rktb-mfwm",
      "hash": "htxdwcdsczlhwwksfxnkrkcwvhwwtrclfmwvhsfnnnvwvbxcnvntblfrrkmbvbfc",
      "size": 145096,
      "link": "https://site.clue.surf/xbbl-dbzk-wrdz-tknz-zwmw-bzct-rktb-mfwm.webp"
    },
    "/term-resized.png": {
      "code": "xkbl-xlmh-nmhf-tvwh-fncc-lkzf-xhdv-mwwh",
      "hash": "dxvrcnwlnrnfbwbxsfczlcxbbxlxctmtvfmwkcvnnkndvkzbvxbzrxcsknnzztxv",
      "size": 523277,
      "link": "https://site.clue.surf/xkbl-xlmh-nmhf-tvwh-fncc-lkzf-xhdv-mwwh.png"
    },
    "/term.png": {
      "code": "wdhc-lvbh-fkkx-tfwm-zfhx-lkwz-ttrt-hcwn",
      "hash": "tkmxtrcrvbfvbzmmsznrhhxxwfkfcvlntszflcftmhlxfknzttwdtnzhkcvbcfsx",
      "size": 332850,
      "link": "https://site.clue.surf/wdhc-lvbh-fkkx-tfwm-zfhx-lkwz-ttrt-hcwn.png"
    },
    "/tone.gif": {
      "code": "dfrn-vsnf-ntkv-tdrv-zkfv-hnkw-rrdt-rlhf",
      "hash": "lttxnkczvmfmnfskmfdmmkxrxkxdbhlrdlslbfhfwvdrctckxwwvczmccmzbvvxw",
      "size": 1458397,
      "link": "https://site.clue.surf/dfrn-vsnf-ntkv-tdrv-zkfv-hnkw-rrdt-rlhf.gif"
    },
    "/vibe.png": {
      "code": "lkml-wdnk-zhww-thnx-vrtz-mdfr-hfxm-vfhc",
      "hash": "dhmhzclddvvfkzmsbkwwddkdtsvrnzbsvtllbmnftrtxvhmhssdcbkxbdsshtdnc",
      "size": 576838,
      "link": "https://site.clue.surf/lkml-wdnk-zhww-thnx-vrtz-mdfr-hfxm-vfhc.png"
    },
    "/voice.png": {
      "code": "lwbd-xwlx-cclf-thfc-xvzz-cbls-wnhd-rrhh",
      "hash": "crzblzkscrlxlhvvdsllhwhlmtvbxvsksmsnrddrzxtxctfsxhzlbwlfmdhvhnln",
      "size": 4995411,
      "link": "https://site.clue.surf/lwbd-xwlx-cclf-thfc-xvzz-cbls-wnhd-rrhh.png"
    }
  }
}

const SITE_ASSETS: Readonly<Record<string, AssetEntry>> = MANIFEST.assets

// The <global:asset> namespace binding. `get` throws on an unknown path (misspellings fail at the call site
// instead of producing a broken URL), matching asset.ts's getSiteAssetPath; `tryGet` / `entry` return null.
export const asset = {
  // Resolve a logical asset path (`/CrowMark.otf`) to its current hashed URL. Throws if missing.
  get(logicalPath: string): string {
    const entry = SITE_ASSETS[logicalPath]
    if (!entry) {
      throw new Error(`Unknown site asset: ${logicalPath}`)
    }
    return entry.link
  },

  // Resolve safely -- null if the asset is missing rather than throwing.
  tryGet(logicalPath: string): string | null {
    return SITE_ASSETS[logicalPath]?.link ?? null
  },

  // The full entry (link + code + hash + size), or null.
  entry(logicalPath: string): AssetEntry | null {
    return SITE_ASSETS[logicalPath] ?? null
  },

  // The bare `assets` table, for direct iteration.
  all(): Readonly<Record<string, AssetEntry>> {
    return SITE_ASSETS
  },

  // The full manifest, for advanced callers.
  manifest(): AssetsManifest {
    return MANIFEST
  },
}
