allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
overrides:
  esbuild: ^0.28.1
  js-yaml: ^4.3.0
  fast-uri: ^3.1.4
  linkify-it: ^5.0.2
  undici: ^7.29.0
  brace-expansion@1: ^1.1.18
  brace-expansion@2: ^2.1.4
  brace-expansion@3: ^5.0.7
  brace-expansion@4: ^5.0.7
