// Generate the deck-manifest and lockfile grammar module FROM THE MILL ROLE FILES.
//
// The package manager reads deck.tree and lock.tree through the mill executor
// (@term/make/code/compile/mill-run), never with hand-rolled extraction. The
// grammar lives in `deck/mill/code/deck/` as `.tree` files; a published
// package cannot read those at run time, so the text is inlined here at build
// time, the same way `make:read` inlines the parser bridge.
//
// The load closure is walked by `grammarTextOf` (make/code/compile/mill-load.ts), which reads each file with the
// real parser and resolves each `load` by the package path rule every resolver calls. This replaced
// task/make-grammar.mjs, which matched `load @term/mill/code/...` lines with a regular expression: a second reader
// of the grammar and a second resolver, which stopped finding a load the moment it was written in the short form.
//
// The output is GENERATED. Never edit it. Run `pnpm run make:grammar`.

import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { grammarTextOf } from '@term/make/code/compile/mill-load'

const here = path.dirname(path.dirname(fileURLToPath(import.meta.url)))
const mill = path.join(here, '..', 'mill', 'code')

function collect(entry: string): string {
  const { text, problems } = grammarTextOf(mill, entry)

  for (const problem of problems) {
    console.log(`  problem: ${problem}`)
  }

  if (problems.length > 0) {
    throw new Error(`make:grammar: ${problems.length} problem(s) reading ${entry}`)
  }

  return text
}

const deckGrammar = collect(path.join(mill, 'deck', 'mine.tree'))
const lockGrammar = collect(path.join(mill, 'deck', 'lock', 'mine.tree'))

const out = path.join(here, 'code', 'grammar.ts')
writeFileSync(
  out,
  `// GENERATED by task/make-grammar.ts from deck/mill/code/deck. Never edit. Run \`pnpm run make:grammar\`.
// The deck-manifest and lockfile grammars, inlined so the published package carries them.

export const DECK_GRAMMAR = ${JSON.stringify(deckGrammar)}

export const LOCK_GRAMMAR = ${JSON.stringify(lockGrammar)}
`,
)
console.log(`wrote ${path.relative(process.cwd(), out)}`)
