// Generate the deck-manifest and lockfile grammar module FROM THE MILL ROLE FILES.
//
// The package manager reads deck.tree and lock.tree through the mill executor
// (@term/make/code/compile/mill-run), never with hand-rolled extraction. The
// grammar lives in `deck/mill/code/deck/` as `.tree` files; a published
// package cannot read those at run time, so the text is inlined here at build
// time, the same way `make:read` inlines the parser bridge.
//
// The output is GENERATED. Never edit it. Run `pnpm run make:grammar`.
import { readFileSync, writeFileSync, existsSync } from 'fs'
import path from 'path'

const here = path.dirname(new URL('.', import.meta.url).pathname)
const mill = path.join(here, '..', 'mill', 'code')

// the deck grammar with its load closure inlined (the executor takes one grammar map)
function collect(entry) {
  const seen = new Set()
  const parts = []

  function walk(file) {
    if (seen.has(file) || !existsSync(file)) {
      return
    }

    seen.add(file)
    const text = readFileSync(file, 'utf8')
    parts.push(text.replace(/^load .*$\n(?:  find .*$\n)*/gm, ''))

    for (const m of text.matchAll(/^load @term\/mill\/code\/(\S+)$/gm)) {
      for (const c of [
        path.join(mill, `${m[1]}.tree`),
        path.join(mill, m[1], 'base.tree'),
      ]) {
        if (existsSync(c)) {
          walk(c)
          break
        }
      }
    }
  }

  walk(entry)

  return parts.join('\n\n')
}

const deckGrammar = collect(path.join(mill, 'deck', 'mine.tree'))
const lockGrammar = collect(path.join(mill, 'deck', 'lock', 'mine.tree'))

const out = path.join(here, '..', 'deck', 'code', 'grammar.ts')
writeFileSync(
  out,
  `// GENERATED by task/make-grammar.mjs from deck/mill/code/deck — never edit. Run \`pnpm run make:grammar\`.
// The deck-manifest and lockfile grammars, inlined so the published package carries them.

export const DECK_GRAMMAR = ${JSON.stringify(deckGrammar)}

export const LOCK_GRAMMAR = ${JSON.stringify(lockGrammar)}
`,
)
console.log(`wrote ${path.relative(process.cwd(), out)}`)
