// Generate zone's tree-reader shim FROM THE COMPILER.
//
// Zone parses `.tree` through the Term compiler, never by hand. The compiler
// lives in `@term/make`; zone's runtime shims are plain source prepended into
// the boot bundle. So the bridge is bundled self-contained and written INTO
// the shim, rather than required at runtime.
//
// Requiring it at runtime was tried and does not hold up: a prepended shim's
// `require` resolves against whichever project is booting, which is the repo
// root from one directory and a package from another, so the path is only
// ever right by accident. Inlining has no resolution step to get wrong.
//
// The output is GENERATED. Never edit it. Run `pnpm run make:read`.
import { build } from 'esbuild'
import { writeFileSync } from 'fs'
import path from 'path'

const here = path.dirname(new URL('.', import.meta.url).pathname)
const out = path.join(here, '..', 'zone', 'code', 'tool', 'runtime', 'mill.ts')

const made = await build({
  entryPoints: [path.join(here, 'code', 'read.ts')],
  bundle: true,
  platform: 'node',
  format: 'iife',
  globalName: '__read',
  write: false,
  // `@term/<name>` is a Term package resolved from its `deck.tree`, not from
  // node_modules, so esbuild is told where each one lives.
  plugins: [
    {
      name: 'term-packages',
      setup(b) {
        b.onResolve({ filter: /^@term\// }, args => {
          const rest = args.path.slice('@term/'.length)
          const cut = rest.indexOf('/')
          const name = cut === -1 ? rest : rest.slice(0, cut)
          const sub = cut === -1 ? '' : rest.slice(cut)
          return { path: path.join(here, '..', name, sub) + '.ts' }
        })
      },
    },
  ],
})

const parser = made.outputFiles[0].text

writeFileSync(
  out,
  `// GENERATED by \`pnpm run make:read\` in @term/deck. Do not edit.
//
// Reading a \`.tree\` file THROUGH THE COMPILER, never by hand.
//
// Every custom \`.tree\` dialect is parsed by the Term compiler into a CST and
// an AST, and integrated by defining a mill. Zone's grammar is at
// \`@term/mill/code/zone\`. What follows is the compiler's own parser and its
// \`read.ts\` bridge, bundled, so this file cannot drift from the language: it
// IS the language's parser.
//
// WHAT THIS REPLACED. 286 hand-written lines that split on spaces, tracked
// indent depth by hand and kept ONE \`<...>\` per line. A line carrying two
// values silently lost the first, so \`time <made>, <toss>\` parsed as a cache
// with no fetch time and read as stale the instant it was written.
//
// The shape returned:
//
//   head   the first word
//   term   the bare words after it, in order
//   code   the FIRST \`<...>\` value, empty when the line carries none
//   more   EVERY \`<...>\` value, in order
//   leaf   nested lines, from an indent or from a comma, in written order

${parser}

const mill = (() => {
  const toLeaf = (form: any): any => ({
    head: String(form.head ?? ''),
    term: (form.terms ?? []).map((one: any) => String(one)),
    code: form.value === undefined ? '' : String(form.value),
    more: (form.values ?? []).map((one: any) => String(one)),
    leaf: (form.forms ?? []).map(toLeaf),
  })

  return {
    read: (text: string): any[] => {
      const got = (__read as any).readTree({ file: 'zone.tree', text })

      if (!got.ok) {
        const first = got.diagnostics?.[0]

        process.stderr.write(
          'The declaration does not parse.\\n\\n  ' +
            String(first?.message ?? 'syntax error') +
            (first?.hint ? '\\n\\n  ' + first.hint : '') +
            '\\n',
        )
        process.exit(1)
      }

      return got.forms.map(toLeaf)
    },
  }
})()
`,
)

console.log('wrote', path.relative(process.cwd(), out))
