// The ONE place the toolchain's directory and environment names are written.
//
// Everything Term keeps on disk lives under `.base/@cluesurf/term/`: a project's build cache, its memory, its boot
// markers and logs, and the user-level auth token, link registry and shared mill cache under `~`.
//
// WHY THIS FILE EXISTS. The path was spelled out `.base/@cluesurf/term` in 59 places across 28 files, so renaming it was 59
// chances to miss one, and a missed one does not fail: it reads an empty cache, or writes a fact into a directory
// nothing looks in. Scoping it under `@cluesurf` is the same change the package names made, and it should be a
// one-line change the next time.
//
// THE OLD LOCATION IS STILL READ, for the things that cannot be rebuilt. A cache is regenerated by the next build
// and nobody notices; a remembered fact, an auth token and a link registry are not, and losing them silently is the
// worst outcome of a rename. `legacyOf` gives the pre-2026-08-30 path so a reader can fall back to it.

import path from 'path'
import os from 'os'
import { existsSync } from 'fs'

// the directory under `.base`, scoped the way the packages are
export const HOME = path.join('@cluesurf', 'term')

// what it was before 2026-08-30, still read for data that cannot be rebuilt
export const LEGACY_HOME = 'term'

// `<root>/.base/@cluesurf/term/<...parts>`
export function projectHome(root: string, ...parts: string[]): string {
  return path.join(root, '.base', HOME, ...parts)
}

// the same path as it was before the rename, for a fallback read
export function legacyProjectHome(
  root: string,
  ...parts: string[]
): string {
  return path.join(root, '.base', LEGACY_HOME, ...parts)
}

// `~/.base/@cluesurf/term/<...parts>`: the user-level auth token, link registry and shared mill cache
export function userHome(...parts: string[]): string {
  return path.join(os.homedir(), '.base', HOME, ...parts)
}

// the same, before the rename
export function legacyUserHome(...parts: string[]): string {
  return path.join(os.homedir(), '.base', LEGACY_HOME, ...parts)
}

// The path to use for something that CANNOT BE REBUILT: a remembered fact, an auth token, a signing key, the link
// registry. If the new location does not exist yet and the old one does, the old one is used, whole. Nothing is
// moved and nothing is split across the two, so a rename cannot lose a file and cannot half-migrate one either.
//
// A cache does NOT go through this. It is regenerated by the next build, and pointing at the old copy would keep a
// stale directory alive forever for no benefit.
export function keptAt(current: string, legacy: string): string {
  return !existsSync(current) && existsSync(legacy) ? legacy : current
}

// The environment variables the toolchain reads. `TERM_` since the Seed rename; the `SEED_` spelling is still
// honored so a shell profile that sets one keeps working, and is the only place the old name survives.
//
// NOTE the prefix is `TERM_` and never bare `TERM`, which is the terminal type every POSIX shell already sets.
export function env(name: string): string | undefined {
  return process.env[`TERM_${name}`] ?? process.env[`SEED_${name}`]
}
