// `term self skill`: write the skill that teaches a coding agent this toolchain's own verbs into the project, at
// `.claude/skills/term/SKILL.md`, where Claude Code finds it. The agent already knows how to edit files and run
// commands. What it cannot know is which command answers which question here, and that each one answers in JSON, so
// the skill is that list and the loop it makes, generated by the version that answers the commands it names.
//
// A file this command did not write is never overwritten: the first line marks the file as generated, and a file
// without it is refused with its path. A file it did write is rewritten when the text differs, so running a newer
// version brings the skill up to date.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { closeRun, field, location, openRun, printData, report, showPath } from '@term/call/code/output'

const MARK = '<!-- written by term self skill. Run it again to update, or delete this line to keep your own edits. -->'

export function skillText(version: string): string {
  return `---
name: term
description: Work in a Term project (.tree files) through the toolchain's agent verbs, each of which answers in JSON. Check one file and apply the compiler's fixes, fill typed holes, look up what a diagnostic means, read one name with what surrounds it, and see what a change lets tasks reach. Use when writing, editing, debugging or reviewing .tree code.
---

${MARK}

# Term

Term programs are \`.tree\` files, built and checked by the \`term\` command (this skill was written by term ${version}).
Every verb below prints JSON with \`--back json\`, and any verb prints one JSON object per event with \`--log json\`.

## The loop

1. Before a change, keep the roll: \`term roll --json > tmp/before.json\`.
2. Write the code. Where a value is not known yet, write \`hole\` (below).
3. Check the file: \`term scan <file> --back json\`. The answer is \`{ ok, diagnostics }\`, and each diagnostic has
   \`name\`, \`code\`, \`severity\`, \`message\`, \`hint\`, \`span\` and \`fixes\`. The exit code is non-zero on any error.
4. Apply the fixes. \`term scan <file> --fix\` writes every fix marked \`sure\` and scans again. A fix with
   \`sure: false\` is a guess among several (a near spelling, an import with two homes, a name that fits a hole): read
   its \`title\`, pick, and apply its \`edits\` yourself. An edit replaces the text at \`span\` (zero-based line and
   column), which must still read \`was\`, with \`text\`.
5. Build the project: \`term make\`. Only the build compiles everything, and \`term scan\` checks one file.
6. Test: \`term test\`, or \`term test <filter>\`.
7. Compare: \`term roll --diff tmp/before.json\`. It names every task whose reach (the native modules it can touch:
   the file system, the network, processes) or raises changed. A task that gained a native module is a warning, so
   \`--strict\` fails the run. Say what gained what when you report the change. \`--diff <git ref>\` compares with a
   commit instead.

## Typed holes

\`hole\` where a value goes, in a place where no local or definition is named \`hole\`, is a gap the checker answers:

- \`term scan\` reports it as \`typed-hole\`, and its message names the type the place needs.
- Its hint lists the names in scope of that type and the tasks that return it.
- Each name in scope of that type is a fix that writes it in.
- A hole whose type nothing decides yet says so. Use it where a type is needed, or give it a value, and scan again.

A program with a hole never builds, so a hole cannot ship.

## Looking things up

- \`term show kink <name or code>\` says what a diagnostic means, what resolves it, and whether a tool writes the
  fix. It takes the name (\`type-mismatch\`), the code as printed (\`0007\`), the number from JSON (\`7\`), or a lint
  code (\`L019\`). \`term show kink --back json\` is the whole catalog.
- \`term show name <task, form or mask>\` is one name with what a reader needs around it: its definition and doc
  comment, the forms its signature names, every use in the project, and the heads of what it calls. \`--budget <tokens>\`
  bounds it (default 4000), and what did not fit is counted.
- \`term look <module>\` lists what a module offers.
- \`term roll task\` lists every task with what it takes, returns, raises and reaches.
  \`term roll exception --path\` shows where each exception comes from.

## Other gates

- \`term lint --fix\` applies the lint rules' fixes, and \`term form\` lays files out canonically.
- \`term hold\` is the proof gate: every file compiles, no claim is open, every obligation is proven.

## Memory

- \`term mind "<fact>" --kind decision\` remembers a fact for the next session. Kinds are \`decision\`, \`convention\`,
  \`constraint\`, \`reference\` and \`note\`.
- \`term mind --find <words> --back json\` recalls facts.
`
}

// the project the skill belongs to: the nearest folder with a deck.tree, else the working folder
function projectRoot(from: string): string {
  for (let dir = path.resolve(from); ; dir = path.dirname(dir)) {
    if (existsSync(path.join(dir, 'deck.tree'))) {
      return dir
    }

    if (path.dirname(dir) === dir) {
      return path.resolve(from)
    }
  }
}

export function callSelfSkill(input: { root: string; version: string; back?: string }): void {
  const json = input.back === 'json'
  const base = projectRoot(input.root)
  const file = path.join(base, '.claude', 'skills', 'term', 'SKILL.md')
  const text = skillText(input.version)
  const before = existsSync(file) ? readFileSync(file, 'utf8') : undefined
  const state = before === undefined ? 'written' : before === text ? 'current' : before.includes(MARK) ? 'updated' : 'kept'

  if (state === 'written' || state === 'updated') {
    mkdirSync(path.dirname(file), { recursive: true })
    writeFileSync(file, text)
  }

  if (json) {
    printData(`${JSON.stringify({ file: path.relative(input.root, file) || file, state })}\n`)

    if (state === 'kept') {
      process.exitCode = 1
    }

    return
  }

  openRun({ verb: 'self', root: input.root, facts: ['skill'] })

  if (state === 'kept') {
    report({
      glyph: 'failed',
      kind: 'problem',
      subject: 'There is a skill file here that term did not write, so it is left as it is',
      fields: [location(showPath(file, input.root))],
    })
    closeRun({ verdict: 'Skill not written', next: 'move that file aside and run term self skill again' })

    return
  }

  if (state !== 'current') {
    report({ glyph: state === 'written' ? 'added' : 'changed', kind: 'change', subject: `Skill ${state}`, fields: [location(showPath(file, input.root)), field('version', input.version)] })
  }

  closeRun({ verdict: state === 'current' ? 'The skill is current' : `The skill is ${state}` })
}
